# Generated by Django 4.2.5 on 2023-12-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoreModels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
