# Generated by Django 4.2.5 on 2023-12-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MoreModels', '0002_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='Users/ProfileImages'),
        ),
    ]
