# Generated by Django 4.2.5 on 2023-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoreModels', '0003_alter_userdetail_bio_alter_userdetail_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(default='Users/default/profile.png', upload_to='Users/ProfileImages'),
        ),
    ]
