# Generated by Django 5.0.1 on 2024-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoreModels', '0004_alter_userdetail_bio_alter_userdetail_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMainPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='Users/default/profile.png', upload_to='Users/ProfileImages')),
            ],
        ),
    ]
