# Generated by Django 5.0.1 on 2024-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MoreModels', '0006_homemainpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemainpage',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
