# Generated by Django 4.2.5 on 2023-10-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateCSSHomeLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='GenerateCSS/Homepage/Images')),
            ],
        ),
    ]
