# Generated by Django 4.2.5 on 2023-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerateCSS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatecsshomelinks',
            name='color',
            field=models.CharField(default='#FFC0C7', max_length=7),
            preserve_default=False,
        ),
    ]
